import { Author, Article, Tag, Pillar } from '@/types';

export const mockAuthors: Author[] = [
    {
        id: '1',
        name: 'Sarah Mitchell',
        title: 'Chief Compliance Officer',
        bio: 'Sarah has over 15 years of experience in regulatory compliance and has helped hundreds of RIAs navigate complex SEC requirements.',
        photo: 'https://placehold.co/400x400/49648C/FFFFFF?text=SM',
        linkedin: 'https://linkedin.com/in/sarahmitchell',
        email: 'sarah@regulatethis.com',
    },
    {
        id: '2',
        name: 'David Chen',
        title: 'Technology Strategy Director',
        bio: 'David specializes in helping wealth management firms leverage technology for operational efficiency and better client outcomes.',
        photo: 'https://placehold.co/400x400/49648C/FFFFFF?text=DC',
        linkedin: 'https://linkedin.com/in/davidchen',
        email: 'david@regulatethis.com',
    },
    {
        id: '3',
        name: 'Emily Rodriguez',
        title: 'Practice Management Consultant',
        bio: 'Emily works with RIA owners to scale their practices while maintaining exceptional client service and team culture.',
        photo: 'https://placehold.co/400x400/49648C/FFFFFF?text=ER',
        linkedin: 'https://linkedin.com/in/emilyrodriguez',
        email: 'emily@regulatethis.com',
    },
];

export const mockTags: Tag[] = [
    { id: '1', name: 'AI in Wealth Management', slug: 'ai-wealth-management' },
    { id: '2', name: 'SEC Audits', slug: 'sec-audits' },
    { id: '3', name: 'CRM Systems', slug: 'crm-systems' },
    { id: '4', name: 'RIA Growth', slug: 'ria-growth' },
    { id: '5', name: 'Options Strategies', slug: 'options-strategies' },
    { id: '6', name: 'FINRA Regulation', slug: 'finra-regulation' },
    { id: '7', name: 'Automation', slug: 'automation' },
    { id: '8', name: 'Succession Planning', slug: 'succession-planning' },
];

export const mockArticles: Article[] = [
    {
        id: '1',
        title: 'The 2025 SEC Examination Priorities: What RIAs Need to Know',
        subtitle: 'A comprehensive breakdown of the latest regulatory focus areas',
        slug: '2025-sec-examination-priorities',
        content: 'Full article content here...',
        excerpt: 'The SEC has released its examination priorities for 2025, with significant focus on AI usage, cybersecurity, and ESG disclosures. Here\'s what your firm needs to prepare for.',
        pillar: 'Compliance & Regulation',
        tags: [mockTags[1], mockTags[5]],
        author: mockAuthors[0],
        featuredImage: 'https://placehold.co/1200x600/0B1F3B/FFFFFF?text=SEC+Priorities',
        publishDate: '2024-12-20',
        readTime: 8,
        isFeatured: true,
    },
    {
        id: '2',
        title: 'AI in Wealth Management: Beyond the Hype to Practical Applications',
        subtitle: 'Real-world use cases that are transforming advisory practices',
        slug: 'ai-wealth-management-practical-applications',
        content: 'Full article content here...',
        excerpt: 'While everyone talks about AI, few advisors know how to actually implement it. We explore proven use cases that deliver measurable ROI.',
        pillar: 'Technology & Operations',
        tags: [mockTags[0], mockTags[6]],
        author: mockAuthors[1],
        featuredImage: 'https://placehold.co/1200x600/0B1F3B/FFFFFF?text=SEC+Priorities',
        publishDate: '2024-12-18',
        readTime: 10,
    },
    {
        id: '3',
        title: 'From $500M to $5B AUM: Lessons from High-Growth RIAs',
        subtitle: 'The operational infrastructure that enables scale',
        slug: 'high-growth-rias-lessons',
        content: 'Full article content here...',
        excerpt: 'We studied 20 RIAs that achieved 10x growth in under a decade. Here are the common patterns in their approach to scaling.',
        pillar: 'Practice Management',
        tags: [mockTags[3], mockTags[7]],
        author: mockAuthors[2],
        featuredImage: 'https://placehold.co/1200x600/0B1F3B/FFFFFF?text=RIA+Growth',
        publishDate: '2024-12-15',
        readTime: 12,
    },
    {
        id: '4',
        title: 'Beyond Covered Calls: A Framework for Systematic Income',
        subtitle: 'Advanced options strategies for sophisticated portfolios',
        slug: 'systematic-income-framework',
        content: 'Full article content here...',
        excerpt: 'Covered calls are just the beginning. Discover how to build a comprehensive income generation strategy using multiple options approaches.',
        pillar: 'Client Strategy',
        tags: [mockTags[4]],
        author: mockAuthors[1],
        featuredImage: 'https://placehold.co/1200x600/0B1F3B/FFFFFF?text=Options+Income',
        publishDate: '2024-12-12',
        readTime: 15,
    },
    {
        id: '5',
        title: 'The State of RIA Technology in 2025',
        subtitle: 'Industry benchmark report on technology adoption',
        slug: 'state-of-ria-technology-2025',
        content: 'Full article content here...',
        excerpt: 'Our annual survey of 500+ RIAs reveals surprising trends in technology spending, satisfaction, and future priorities.',
        pillar: 'Industry Insights',
        tags: [mockTags[2], mockTags[0]],
        author: mockAuthors[1],
        featuredImage: 'https://placehold.co/1200x600/0B1F3B/FFFFFF?text=Tech+Report',
        publishDate: '2024-12-10',
        readTime: 20,
    },
    {
        id: '6',
        title: 'How AI Supervision is Transforming Compliance',
        subtitle: 'Automation strategies for modern RIAs',
        slug: 'ai-supervision-compliance',
        content: 'Full article content here...',
        excerpt: 'AI-powered supervision tools are changing how RIAs monitor advisor communications and ensure regulatory compliance.',
        pillar: 'Technology & Operations',
        tags: [mockTags[0], mockTags[1]],
        author: mockAuthors[1],
        featuredImage: 'https://placehold.co/1200x600.png?text=AI+Supervision',
        publishDate: '2024-12-08',
        readTime: 9,
    },
    {
        id: '7',
        title: 'Building a Scalable RIA: Lessons from $10B Firms',
        subtitle: 'Infrastructure requirements for rapid growth',
        slug: 'scalable-ria-infrastructure',
        content: 'Full article content here...',
        excerpt: 'What does it take to scale from boutique to enterprise? We break down the technology, people, and processes required.',
        pillar: 'Practice Management',
        tags: [mockTags[3], mockTags[7]],
        author: mockAuthors[2],
        featuredImage: 'https://placehold.co/1200x600.png?text=Scalable+RIA',
        publishDate: '2024-12-05',
        readTime: 14,
    },
    {
        id: '8',
        title: 'The New SEC Marketing Rule: Practical Implementation',
        subtitle: 'Compliance checklist for 2025',
        slug: 'sec-marketing-rule-implementation',
        content: 'Full article content here...',
        excerpt: 'Two years after the SEC marketing rule changes, many RIAs still struggle with implementation. Here\'s a practical guide.',
        pillar: 'Compliance & Regulation',
        tags: [mockTags[1], mockTags[5]],
        author: mockAuthors[0],
        featuredImage: 'https://placehold.co/1200x600.png?text=SEC+Marketing+Rule',
        publishDate: '2024-12-03',
        readTime: 11,
    },
    {
        id: '9',
        title: 'Alternative Investments for HNW Clients',
        subtitle: 'Beyond traditional 60/40 portfolios',
        slug: 'alternative-investments-hnw',
        content: 'Full article content here...',
        excerpt: 'Private equity, hedge funds, and real assets are becoming table stakes for high-net-worth advisory practices.',
        pillar: 'Client Strategy',
        tags: [mockTags[4]],
        author: mockAuthors[1],
        featuredImage: 'https://placehold.co/1200x600.png?text=Alternative+Investments',
        publishDate: '2024-12-01',
        readTime: 13,
    },
    {
        id: '10',
        title: 'The Future of Financial Planning: AI and Human Advisors',
        subtitle: 'Industry predictions for the next decade',
        slug: 'future-financial-planning-ai',
        content: 'Full article content here...',
        excerpt: 'Will AI replace financial advisors? Our analysis of technology trends and the enduring value of human judgment.',
        pillar: 'Industry Insights',
        tags: [mockTags[0], mockTags[2]],
        author: mockAuthors[1],
        featuredImage: 'https://placehold.co/1200x600.png?text=Future+of+Planning',
        publishDate: '2024-11-28',
        readTime: 16,
    },
    {
        id: '11',
        title: 'Cybersecurity Essentials for RIAs',
        subtitle: 'Protecting client data in 2025',
        slug: 'cybersecurity-essentials-rias',
        content: 'Full article content here...',
        excerpt: 'With increasing SEC focus on cybersecurity, RIAs need robust protection strategies. Here\'s your essential checklist.',
        pillar: 'Technology & Operations',
        tags: [mockTags[2], mockTags[6]],
        author: mockAuthors[1],
        featuredImage: 'https://placehold.co/1200x600.png?text=Cybersecurity',
        publishDate: '2024-11-25',
        readTime: 10,
    },
    {
        id: '12',
        title: 'Advisor Compensation Models That Drive Performance',
        subtitle: 'Aligning incentives with firm growth',
        slug: 'advisor-compensation-models',
        content: 'Full article content here...',
        excerpt: 'The right compensation structure can make or break your talent retention strategy. Here\'s what top firms are doing.',
        pillar: 'Practice Management',
        tags: [mockTags[3], mockTags[7]],
        author: mockAuthors[2],
        featuredImage: 'https://placehold.co/1200x600.png?text=Compensation+Models',
        publishDate: '2024-11-22',
        readTime: 12,
    },
    {
        id: '13',
        title: 'Tax-Loss Harvesting in Volatile Markets',
        subtitle: 'Maximizing client value through strategic selling',
        slug: 'tax-loss-harvesting-strategy',
        content: 'Full article content here...',
        excerpt: 'Market volatility creates tax-loss harvesting opportunities. Learn how to systematically add value for clients.',
        pillar: 'Client Strategy',
        tags: [mockTags[4]],
        author: mockAuthors[1],
        featuredImage: 'https://placehold.co/1200x600.png?text=Tax+Loss+Harvesting',
        publishDate: '2024-11-20',
        readTime: 8,
    },
    {
        id: '14',
        title: 'The M&A Boom in Wealth Management',
        subtitle: 'Market analysis and valuation trends',
        slug: 'ma-boom-wealth-management',
        content: 'Full article content here...',
        excerpt: 'RIA consolidation continues at record pace. What\'s driving valuations and what does it mean for independent advisors?',
        pillar: 'Industry Insights',
        tags: [mockTags[3]],
        author: mockAuthors[2],
        featuredImage: 'https://placehold.co/1200x600.png?text=M&A+Boom',
        publishDate: '2024-11-18',
        readTime: 15,
    },
    {
        id: '15',
        title: 'Form ADV Part 2 Brochure: Common Mistakes',
        subtitle: 'Compliance pitfalls to avoid',
        slug: 'form-adv-common-mistakes',
        content: 'Full article content here...',
        excerpt: 'SEC examiners consistently find the same errors in Form ADV disclosures. Here\'s how to avoid them.',
        pillar: 'Compliance & Regulation',
        tags: [mockTags[1], mockTags[5]],
        author: mockAuthors[0],
        featuredImage: 'https://placehold.co/1200x600.png?text=Form+ADV+Mistakes',
        publishDate: '2024-11-15',
        readTime: 7,
    },
];

// Helper functions
export const getFeaturedArticle = (): Article | undefined => {
    return mockArticles.find(article => article.isFeatured);
};

export const getRecentArticles = (limit: number = 9): Article[] => {
    return mockArticles
        .sort((a, b) => new Date(b.publishDate).getTime() - new Date(a.publishDate).getTime())
        .slice(0, limit);
};

export const getArticlesByPillar = (pillar: Pillar): Article[] => {
    return mockArticles.filter(article => article.pillar === pillar);
};

export const getIndustryInsightsArticles = (limit: number = 3): Article[] => {
    return mockArticles
        .filter(article => article.pillar === 'Industry Insights')
        .slice(0, limit);
};