import type { NotificationItem, Connection, Conversation } from '@/types/dashboard';

export const mockNotifications: NotificationItem[] = [
  {
    id: '1',
    accountId: 'friendy tan',
    senderName: 'Dayanullah Khan',
    messagePreview:
      'Hi Tan, thanks again for your help. If you get a chance, could you please speak with Vicky or any hiring manager regardi...',
    isRead: false,
    timeAgo: '2d ago',
    type: 'message',
  },
  {
    id: '2',
    accountId: 'friendy tan',
    senderName: 'Dayanullah Khan',
    messagePreview: 'Okay, thanks',
    isRead: false,
    timeAgo: '3d ago',
    type: 'message',
  },
  {
    id: '3',
    accountId: 'friendy tan',
    senderName: 'Vaibhav Shresth',
    messagePreview: 'Hi, thanks for connecting! Happy to network.',
    isRead: false,
    timeAgo: '3d ago',
    type: 'message',
  },
  {
    id: '4',
    accountId: 'rendy yankee',
    senderName: 'LinkedIn Team',
    messagePreview: 'You have a new connection request from Sarah Mitchell.',
    isRead: true,
    timeAgo: '4d ago',
    type: 'connection',
  },
  {
    id: '5',
    accountId: 'friendy tan',
    senderName: 'AMIT ANAND',
    messagePreview: 'Great to connect! I saw your profile and wanted to reach out.',
    isRead: true,
    timeAgo: '5d ago',
    type: 'message',
  },
  {
    id: '6',
    accountId: 'rendy yankee',
    senderName: 'Siddharth Agarwal',
    messagePreview: 'Hi Rendy, I came across your profile and was impressed by your experience.',
    isRead: false,
    timeAgo: '5d ago',
    type: 'message',
  },
  {
    id: '7',
    accountId: 'friendy tan',
    senderName: 'Guneeta Bhambra',
    messagePreview: 'Congratulations on your new role! Looking forward to staying connected.',
    isRead: true,
    timeAgo: '6d ago',
    type: 'message',
  },
  {
    id: '8',
    accountId: 'rendy yankee',
    senderName: 'Tech Recruiter',
    messagePreview: 'I have an exciting opportunity that might interest you...',
    isRead: false,
    timeAgo: '7d ago',
    type: 'invitation',
  },
  {
    id: '9',
    accountId: 'friendy tan',
    senderName: 'Sarah Mitchell',
    messagePreview: 'Would love to discuss collaboration opportunities.',
    isRead: true,
    timeAgo: '8d ago',
    type: 'connection',
  },
  {
    id: '10',
    accountId: 'rendy yankee',
    senderName: 'James Robertson',
    messagePreview: 'Hi, I noticed we have mutual connections. Would love to connect!',
    isRead: true,
    timeAgo: '9d ago',
    type: 'message',
  },
];

export const mockConnections: Connection[] = [
  {
    id: '1',
    accountId: 'friendy tan',
    fullName: 'AMIT ANAND',
    initials: 'AA',
    headline: 'Engineering Leader | Head of Tech @ K12 | EdTech Innovator',
    connectedAt: '5d ago',
  },
  {
    id: '2',
    accountId: 'friendy tan',
    fullName: 'Vaibhav Shresth',
    initials: 'VS',
    headline: 'Analyst | AI-Driven Process Automation | Strategy',
    connectedAt: '6d ago',
  },
  {
    id: '3',
    accountId: 'friendy tan',
    fullName: 'Siddharth Agarwal',
    initials: 'SA',
    headline: 'Associate Consultant | Digital Transformation',
    connectedAt: '7d ago',
  },
  {
    id: '4',
    accountId: 'friendy tan',
    fullName: 'Guneeta Bhambra',
    initials: 'GB',
    headline: 'Global Operations | Fortune 500 | Strategic Partnerships',
    connectedAt: '8d ago',
  },
  {
    id: '5',
    accountId: 'rendy yankee',
    fullName: 'Friendy Tan',
    initials: 'FT',
    headline: 'Entrepreneur | Growth Hacker | LinkedIn Automation',
    connectedAt: '9d ago',
  },
  {
    id: '6',
    accountId: 'rendy yankee',
    fullName: 'Sarah Mitchell',
    initials: 'SM',
    headline: 'Sr. Product Manager | SaaS | B2B Growth',
    connectedAt: '10d ago',
  },
  {
    id: '7',
    accountId: 'friendy tan',
    fullName: 'James Robertson',
    initials: 'JR',
    headline: 'Head of Sales | Enterprise Software | Cloud Solutions',
    connectedAt: '11d ago',
  },
  {
    id: '8',
    accountId: 'rendy yankee',
    fullName: 'Priya Nair',
    initials: 'PN',
    headline: 'Data Scientist | ML Engineer | NLP Researcher',
    connectedAt: '12d ago',
  },
  {
    id: '9',
    accountId: 'friendy tan',
    fullName: 'Kevin Liu',
    initials: 'KL',
    headline: 'Product Designer | UX Research | Design Systems',
    connectedAt: '13d ago',
  },
  {
    id: '10',
    accountId: 'rendy yankee',
    fullName: 'Maria Santos',
    initials: 'MS',
    headline: 'Marketing Director | Brand Strategy | Content',
    connectedAt: '14d ago',
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    accountId: 'friendy tan',
    participant: 'Dayanullah Khan',
    participantInitials: 'DK',
    lastMessage: 'Hi Tan, thanks again for your help. If you get a chance...',
    lastMessageTime: '2d ago',
    unreadCount: 9,
    isNewContact: true,
    messages: [
      {
        id: 'm1',
        senderName: 'Dayanullah Khan',
        senderInitials: 'DK',
        body: 'How are you?',
        sentAt: '2026-03-06T18:49:00Z',
        isOwnMessage: false,
      },
      {
        id: 'm2',
        senderName: 'friendy tan',
        senderInitials: 'FT',
        body: "I'm good, thanks for asking! How can I help you?",
        sentAt: '2026-03-08T19:51:00Z',
        isOwnMessage: true,
      },
      {
        id: 'm3',
        senderName: 'Dayanullah Khan',
        senderInitials: 'DK',
        body: 'Hi Tan, thanks again for your help. If you get a chance, could you please speak with Vicky or any hiring manager regarding my application?',
        sentAt: '2026-03-10T10:30:00Z',
        isOwnMessage: false,
      },
      {
        id: 'm4',
        senderName: 'Dayanullah Khan',
        senderInitials: 'DK',
        body: 'Okay, thanks',
        sentAt: '2026-03-10T11:45:00Z',
        isOwnMessage: false,
      },
    ],
  },
  {
    id: 'conv-2',
    accountId: 'rendy yankee',
    participant: 'LinkedIn Team',
    participantInitials: 'TL',
    lastMessage: 'Hi Rendy, you have new connection suggestions this week.',
    lastMessageTime: '4d ago',
    unreadCount: 2,
    isNewContact: false,
    messages: [
      {
        id: 'm5',
        senderName: 'LinkedIn Team',
        senderInitials: 'TL',
        body: 'Hi Rendy, you have new connection suggestions this week.',
        sentAt: '2026-03-08T09:00:00Z',
        isOwnMessage: false,
      },
      {
        id: 'm6',
        senderName: 'LinkedIn Team',
        senderInitials: 'TL',
        body: 'Check out people you may know in your industry.',
        sentAt: '2026-03-08T09:01:00Z',
        isOwnMessage: false,
      },
    ],
  },
  {
    id: 'conv-3',
    accountId: 'friendy tan',
    participant: 'Vaibhav Shresth',
    participantInitials: 'VS',
    lastMessage: 'Hi, thanks for connecting! Happy to network.',
    lastMessageTime: '3d ago',
    unreadCount: 0,
    isNewContact: true,
    messages: [
      {
        id: 'm7',
        senderName: 'Vaibhav Shresth',
        senderInitials: 'VS',
        body: 'Hi, thanks for connecting! Happy to network.',
        sentAt: '2026-03-09T14:22:00Z',
        isOwnMessage: false,
      },
      {
        id: 'm8',
        senderName: 'friendy tan',
        senderInitials: 'FT',
        body: 'Thanks Vaibhav! Great to connect with you too.',
        sentAt: '2026-03-09T15:00:00Z',
        isOwnMessage: true,
      },
    ],
  },
  {
    id: 'conv-4',
    accountId: 'rendy yankee',
    participant: 'Siddharth Agarwal',
    participantInitials: 'SA',
    lastMessage: 'Hi Rendy, I came across your profile and was impressed.',
    lastMessageTime: '5d ago',
    unreadCount: 1,
    isNewContact: true,
    messages: [
      {
        id: 'm9',
        senderName: 'Siddharth Agarwal',
        senderInitials: 'SA',
        body: 'Hi Rendy, I came across your profile and was impressed by your experience in the field.',
        sentAt: '2026-03-07T08:15:00Z',
        isOwnMessage: false,
      },
    ],
  },
];
